add support for fan_speed on climate device
XKNX/xknx pull request #1572
Opened 2024-09-16 18:00 UTC by somdoron

## Description

Add fan speed support to climate device. 

Fixes #466

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests

## Checklist

- [X] The documentation has been adjusted accordingly
- [X] Tests have been added that prove the fix is effective or that the feature works
- [X] The changes are documented in the changelog (docs/changelog.md)

2024-09-17 06:56 UTC, farmio requested changes

2024-09-17 06:56 UTC, farmio commented on docs/climate.md
>  climate = Climate(
The new attributes should be added to `Climate`, not `ClimateMode`.

2024-09-17 06:56 UTC, farmio commented on test/devices_tests/climate_test.py
> +        assert telegram == Telegram(
```suggestion
        await climate_step.set_fan_speed(3)
        assert xknx.telegrams.qsize() == 1
        telegram = xknx.telegrams.get_nowait()
        assert telegram == Telegram(
```

2024-09-17 07:02 UTC, farmio commented
Thank you very much! 👍

Do you plan to add this to the HA integration too?

I wonder if it would make sense to create a new device (from HA or in xknx.devices.Climate - like done for ClimateMode) to keep the climate module scope more clean -> 
Climate -> temperatures (and on/off 😬)
ClimateMode -> modes and presets
ClimateFan -> fan speed, fan modes, swing modes and whatever else a climate fan does... (maybe even xknx.devices.Fan can be reused for this) https://developers.home-assistant.io/docs/core/entity/climate
What do you think?

2024-09-17 20:45 UTC, somdoron commented on xknx/devices/climate.py
> +        self.fan_max_step = fan_max_step
I removed the field. I can add those checks, but I want to keep it similar to how fan device works.

2024-09-17 20:53 UTC, somdoron commented
I do plan to add this to Home Assistant. I don't have a strong opinion on how to integrate it, but from Home Assistant's perspective, fan speed is part of the climate device, so it makes sense to handle it the same way here. Additionally, the "switch" for the fan speed is actually the climate switch, so I wouldn't use the fan device for controlling the climate fan speed.

As for using a different class for ClimateFan, I think it would be relatively thin compared to ClimateMode, but I'm fine with moving it to its own class.

2024-09-17 21:34 UTC, farmio commented
> I do plan to add this to Home Assistant.

Nice 👍 let me know if any questions arise.

>  Additionally, the "switch" for the fan speed is actually the climate switch

Yes sure, but afaik the "switch" of the xknx Fan device is optional. I don't have a strong opinion about using this vs. a new class vs. putting it in xknx Climate (and I personally don't own any fans 🙃 whatsoever)

> I think it would be relatively thin compared to ClimateMode

... which is probably a good thing 😛 Was just looking at #466 and thought there could be more to come regarding vane stuff. But could of course always be refactored later on if needed.

Looking at HA climate entity documentation, it seems they don't support percentage fan speeds, but only modes like `[LOW, MEDIUM, HIGH]` (or custom). Do you already have plans on how to integrate that?

2024-09-18 13:30 UTC, farmio approved these changes

2024-09-18 15:06 UTC, marvin-w approved these changes
Nice! Thanks!

2024-09-18 15:06 UTC, merged

2024-09-18 15:11 UTC, adorobis commented
> Fixes #466

Great work. Does implement also the swing mode (as described in the feature request) or only the fan speed?

2024-09-18 15:46 UTC, farmio commented
@adorobis this PR only adds fan speed.

@somdoron I usually implement my HA integration changes and tests locally with a non-released version of xknx so I can still make additions or changes if necessary. Let me know if you want to do the same - and if so, when it is ready for release so we can publish (which will be needed in order to file the HA core PR).